### ISSUE TITLE
3.3 compatible version

### ISSUE THREAD

**Issue by brendanzab** [unitb/lean-lib#1]
These classes and lemmas look really handy! I was wondering if it would be possible to tag a 3.3 compatible release, with the correct version specified in the `lean_version` field in the `leanpkg.toml`?

**Comment by cipher1024** [comment]
That's a great idea thank you! I'll get right on that. As it is, the commit referred to in .travis.yml is 8 days prior to version 3.3 so it might work as is. I'll make sure.

I can't find documentation for the `lean_version` field. Can you point me to some?

I hope it turns out useful :) Please let me know what turns out useful or awkward.

**Comment by cipher1024** [comment]
It is now ported to Lean 3.3

**Comment by brendanzab** [comment]
Yeah, I got a warning that it was expecting the `"master"` lean version, as [specified in the leanpkg](https://github.com/unitb/lean-lib/blob/master/leanpkg.toml#L4), but that I was using lean 3.3, and to change that field. I'm not sure what to though.

**Comment by cipher1024** [comment]
I did not notice that field got added. I'll just try to set it to 3.3.

**Comment by cipher1024** [comment]
Please let me know if that solves your issue.

**Comment by brendanzab** [comment]
I tried using `leanpkg add`, but it failed:

```
➜  lean git:(brendanzab/simple) ✗ leanpkg add https://github.com/unitb/lean-lib
lean-lib: trying to update _target/deps/lean-lib to revision lean-3.3.0
> git fetch    # in directory _target/deps/lean-lib
lean-lib: cloning https://github.com/unitb/lean-lib to _target/deps/lean-lib
> rm -rf _target/deps/lean-lib
> mkdir -p _target/deps/lean-lib
> git clone https://github.com/unitb/lean-lib _target/deps/lean-lib
Cloning into '_target/deps/lean-lib'...
remote: Counting objects: 609, done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 609 (delta 20), reused 26 (delta 10), pack-reused 570
Receiving objects: 100% (609/609), 131.21 KiB | 134.00 KiB/s, done.
Resolving deltas: 100% (348/348), done.
cannot find revision lean-3.3.0 in repository _target/deps/lean-lib
```

I'm guessing that its was looking for a `lean-3.3.0` tag?

Instead I just manually added the following to be `leanpkg.toml` and ran `lean configure`:

```toml
lean-lib = { git = "https://github.com/unitb/lean-lib", rev = "95931ba5f77e512b4c97b21b1871306968628655" }
```

That seemed to work!

**Comment by cipher1024** [comment]
There now is a lean-3.3.0 branch. I'm hoping to be able to keep the latest version of the library working with a few versions of Lean as they keep coming out. `leanpkg add` should now work.

**Comment by brendanzab** [comment]
Thanks a bunch!

**Comment by brendanzab** [comment]
I'm also wondering how much of lean-lib could be upstreamed to lean itself?

**Comment by cipher1024** [comment]
Thanks for the feedback! 

I think a fair portion of it could be merged into Lean or mathlib. I want to be careful in how I submit pull requests to not submit stuff over and over again. But I think it might be worth polishing `traversable` and `foldable` and submitting them.

**Comment by brendanzab** [comment]
Yup, definitely. Good to keep agile first as it becomes harder to change things once they're merged!

**Comment by brendanzab** [comment]
Btw, I really wish the lean formatting would be more generous with indentation... can be pretty hard to read the files at times 😭 

eg: https://gist.github.com/brendanzab/1fd40f178351579dd1afb7cc13cf9b37

**Comment by cipher1024** [comment]
I'm with you on that. I've been wondering about the rationale for a while. I'm wondering if it's used as an incentive to keep proofs short.

**Comment by brendanzab** [comment]
Might call for an issue on the lean repo - but yes, this is done! 👏

**Comment by cipher1024** [comment]
*bows* :D Next, I'll have to figure out where to push each element. Maybe I should push to mathlib and let the maintainer pull to the Lean library once they're comfortable with it.
